services:
  - type: web
    name: flask-ocr-image
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:10000 app:app"
    plan: free


# # Not using cuurently

# services:
#   - type: web
#     name: flask-tesseract-ocr
#     env:
#       PATH: $PATH:/usr/bin/tesseract
#     buildCommand: |
#       echo "Starting build command..."
#       apt-get update
#       apt-get install -y tesseract-ocr
#       pip install -r requirements.txt
#       echo "Build command completed."
#     startCommand: gunicorn -w 4 app:app