# for deploying on render.com 

services:
  - type: web
    name: flask-tesseract-ocr
    env:
      PATH: $PATH:/usr/bin/tesseract
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr
      pip install -r requirements.txt
    startCommand: gunicorn -w 4 app:app